# -*- mode: python ; coding: utf-8 -*-
import os
from pathlib import Path

block_cipher = None

# Find the Qwen3 model directory
model_dir = Path(__file__).parent / "Qwen3-Embedding-0.6B-GGUF"
model_file = model_dir / "Qwen3-Embedding-0.6B-Q8_0.gguf"

a = Analysis(
    ["smp/cli.py"],
    pathex=[str(Path(__file__).parent)],
    binaries=[],
    datas=[
        # Embed the model file
        (str(model_file), "models"),
        # Embed all package data
        ("smp", "smp"),
    ],
    hiddenimports=[
        "smp.core.models",
        "smp.core.config",
        "smp.embedding.service",
        "smp.embedding",
        "smp.vector.mmap_vector",
        "smp.store.graph.mmap_store",
        "smp.store.graph.parser",
        "smp.store.graph",
        "smp.protocol.server",
        "smp.protocol.handlers",
        "smp.protocol.handlers.vector",
        "smp.protocol.handlers.query",
        "smp.protocol.handlers.graph",
        "smp.protocol.handlers.memory",
        "smp.protocol.handlers.enrichment",
        "smp.protocol.handlers.annotate",
        "smp.protocol.handlers.tag",
        "smp.protocol.handlers.session",
        "smp.protocol.handlers.review",
        "smp.protocol.handlers.impact",
        "smp.protocol.handlers.trace",
        "smp.protocol.handlers.navigate",
        "smp.protocol.handlers.context",
        "smp.protocol.handlers.locate",
        "smp.protocol.handlers.search",
        "smp.protocol.handlers.flow",
        "smp.protocol.handlers.plan",
        "smp.protocol.handlers.conflict",
        "smp.protocol.handlers.why",
        "smp.protocol.handlers.diff",
        "smp.protocol.handlers.telemetry",
        "smp.protocol.handlers.dryrun",
        "smp.protocol.handlers.checkpoint",
        "smp.protocol.handlers.lock",
        "smp.protocol.handlers.unlock",
        "smp.protocol.handlers.rollback",
        "smp.protocol.handlers.audit",
        "smp.protocol.handlers.recover",
        "smp.protocol.handlers.enrich_stale",
        "smp.protocol.handlers.enrich_status",
        "smp.protocol.handlers.annotate_bulk",
        "smp.protocol.handlers.annotate",
        "smp.protocol.handlers.batch_update",
        "smp.protocol.handlers.reindex",
        "smp.protocol.handlers.update",
        "smp.protocol.handlers.community",
        "smp.protocol.handlers.sync",
        "smp.protocol.handlers.integrity",
        "smp.protocol.handlers.import_index",
        "smp.protocol.handlers.vector",
        "smp.protocol.handlers.session_open",
        "smp.protocol.handlers.session_close",
        "smp.protocol.handlers.session_recover",
        "smp.protocol.handlers.stats",
        "smp.protocol.handlers.hot",
        "smp.protocol.handlers.node",
        "smp.protocol.handlers.pr_create",
        "smp.protocol.handlers.review_create",
        "smp.protocol.handlers.review_approve",
        "smp.protocol.handlers.review_comment",
        "smp.protocol.handlers.review_reject",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "pytest",
        "unittest",
        "matplotlib",
        "scipy",
        "pandas",
        "IPython",
        "jupyter",
        "notebook",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="smp",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
