from __future__ import annotations

import asyncio
import logging
import uuid
from pathlib import Path

from vibecoder.agent.fuzzy_editor import apply_edit_fuzzy
from vibecoder.company.event_bus import Event
from vibecoder.company.infrastructure import DockerOrchestrator
from vibecoder.company.leadership import ActorMessage, BaseActor
from vibecoder.company.state import CorporateMemory, PullRequest, SystemArchitecture, Ticket

logger = logging.getLogger(__name__)


class DeveloperAgent(BaseActor):
    """Generic FE/BE developer that executes tickets and emits structured PR payloads."""

    def __init__(self, *, name: str, role: str, bus, memory: CorporateMemory, workspace: Path | None = None) -> None:
        super().__init__(name=name, bus=bus, memory=memory)
        self.role = role
        self.workspace = workspace or Path.cwd()

    def register(self) -> None:
        self.bus.subscribe("ticket_assigned", self._enqueue)

    async def _enqueue(self, event: Event) -> None:
        if event.payload.get("assignee") != self.name:
            return
        ticket_id = str(event.payload.get("ticket_id", ""))
        ticket = self.memory.get("tickets", ticket_id)
        if ticket is None:
            return
        await self.inbox.put(ActorMessage(topic="execute_ticket", payload=ticket.model_dump(mode="json"), sender=event.sender))

    async def handle_message(self, message: ActorMessage) -> None:
        if message.topic != "execute_ticket":
            return

        ticket = Ticket.model_validate(message.payload)
        architectures = self.memory.list("system_architectures", limit=1)
        architecture = SystemArchitecture.model_validate(architectures[0].model_dump()) if architectures else None

        artifact_path = await asyncio.to_thread(self._implement_ticket, ticket, architecture)
        pr = PullRequest(
            id=f"pr-{uuid.uuid4().hex[:8]}",
            ticket_id=ticket.id,
            title=f"[{self.role}] {ticket.title}",
            description=f"Automated implementation by {self.name}",
            branch=f"auto/{ticket.id}",
            files_changed=[str(artifact_path)],
            checks={"unit": "pending", "lint": "pending"},
        )
        self.memory.upsert(pr)

        ticket.status = "review"
        self.memory.upsert(ticket)
        await self.bus.publish(Event(topic="pull_request_opened", sender=self.name, payload=pr.model_dump(mode="json")))

    def _implement_ticket(self, ticket: Ticket, architecture: SystemArchitecture | None) -> Path:
        output_file = self.workspace / "vibecoder" / "company" / "autogenerated" / f"{ticket.id}.md"
        output_file.parent.mkdir(parents=True, exist_ok=True)
        architecture_title = architecture.title if architecture else "No architecture found"

        base_content = (
            f"# Ticket Delivery\n\n"
            f"- Ticket: {ticket.id}\n"
            f"- Title: {ticket.title}\n"
            f"- Role: {self.role}\n"
            f"- Architecture: {architecture_title}\n"
        )

        templated = apply_edit_fuzzy(
            "HEADER\nBODY\n",
            "BODY\n",
            f"{base_content}\n",
            threshold=0.0,
        )
        output_file.write_text(templated, encoding="utf-8")
        return output_file


class DevOpsEngineer(BaseActor):
    """Executes infrastructure tickets and provisions dynamic container environments."""

    def __init__(self, *, bus, memory: CorporateMemory, orchestrator: DockerOrchestrator | None = None) -> None:
        super().__init__(name="DevOpsEngineer", bus=bus, memory=memory)
        self._orchestrator = orchestrator or DockerOrchestrator()

    def register(self) -> None:
        self.bus.subscribe("ticket_created", self._enqueue)

    async def _enqueue(self, event: Event) -> None:
        ticket = Ticket.model_validate(event.payload)
        if ticket.role != "infra":
            return
        await self.inbox.put(ActorMessage(topic="infra_ticket", payload=ticket.model_dump(mode="json"), sender=event.sender))

    async def handle_message(self, message: ActorMessage) -> None:
        if message.topic != "infra_ticket":
            return

        ticket = Ticket.model_validate(message.payload)
        dockerfile = (
            "FROM python:3.11-slim\n"
            "WORKDIR /workspace\n"
            "RUN apt-get update && apt-get install -y --no-install-recommends curl git && rm -rf /var/lib/apt/lists/*\n"
            "RUN pip install --no-cache-dir pytest\n"
            "CMD [\"python\", \"--version\"]\n"
        )
        network_id = await asyncio.to_thread(self._orchestrator.create_network)
        image = await asyncio.to_thread(self._orchestrator.build_image, dockerfile)
        run_output = await asyncio.to_thread(self._orchestrator.run_container, image.tags[0], "python --version")

        ticket.status = "done"
        self.memory.upsert(ticket)
        await self.bus.publish(
            Event(
                topic="infra_ready",
                sender=self.name,
                payload={"ticket_id": ticket.id, "network_id": network_id, "image": image.tags[0], "output": run_output},
            )
        )
